security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
#        chain_provider:
#            chain:
#                providers: [in_memory, db_provider]
#        in_memory:
#            memory:
#                users:
#                    TFAdmin:
#                        password: $2y$13$E1cqFNtrm38VUMEpGAoNWu6y5CZAYAfp9h2GcOY2scsinF5ph2lBy
#                        roles: 'ROLE_ADMIN'
        db_provider:
            entity:
                class: App\Entity\User
                property: username
    encoders:
        App\Entity\User: bcrypt

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            provider: db_provider
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
            logout:
                path: logout
                target: /

    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
