language: php
php:
  - '7.1'
sudo: false
cache:
  directories:
  - "$HOME/.composer/cache/files"
services:
  - mysql
before_script:
  - php bin/console --env=test cache:warmup
  - php bin/console doctrine:migrations:migrate --no-interaction
script:
  - cat codecov.yml | curl --data-binary @- https://codecov.io/validate
  - php bin/phpunit --filter 'App\\Tests\\Controller' --coverage-clover=codecov.xml
  - bash <(curl -s https://codecov.io/bash) -F controllers
  - php bin/phpunit --filter 'App\\Tests\\Form\\Type' --coverage-clover=codecov.xml
  - bash <(curl -s https://codecov.io/bash) -F formtype
  - php bin/phpunit --filter 'App\\Tests\\Repository' --coverage-clover=codecov.xml
  - bash <(curl -s https://codecov.io/bash) -F repository
  - php bin/phpunit --filter 'App\\Tests\\Services' --coverage-clover=codecov.xml
  - bash <(curl -s https://codecov.io/bash) -F service
  - php bin/phpunit --filter 'App\\Tests\\Security' --coverage-clover=codecov.xml
  - bash <(curl -s https://codecov.io/bash) -F security
before_install:
  - chmod +x ./deploy.sh
  - sudo apt-get install sshpass
  - mysql -e 'CREATE DATABASE IF NOT EXISTS tf_test;'
install:
  - composer install
after_success:
  - ./deploy.sh
