language: php
php:
- '7.1'
sudo: false
cache:
  directories:
  - "$HOME/.composer/cache/files"
before_install:
- openssl aes-256-cbc -K $encrypted_649a1e2cb581_key -iv $encrypted_649a1e2cb581_iv
  -in client-secret.json.enc -out .\\client-secret.json -d
- chmod +x ./deploy.sh
- sudo apt-get install lftp
install:
- composer install


deploy:
  provider: gae
        # Skip cleanup so api_key.py and vendored dependencies are still there
  skip_cleanup: true
  keyfile: client-secret.json
  project: helical-analogy-207516
  default: true
