language: php
php:
  - '7.1'
sudo: false
cache:
  directories:
  - "$HOME/.composer/cache/files"
services:
  - mysql
before_script:
  - php bin/console --env=test cache:warmup
  - php bin/console doctrine:migrations:migrate --no-interaction
before_install:
  - chmod +x ./deploy.sh
  - sudo apt-get install sshpass
  - mysql -e 'CREATE DATABASE IF NOT EXISTS tf_test;'
install:
  - composer install
after_success:
  - php vendor/bin/php-coveralls -v
  - ./deploy.sh
