language: php
php:
  - '7.1'
sudo: false
cache:
  directories:
  - "$HOME/.composer/cache/files"
services:
  - mysql
before_script:
  - php bin/console --env=test cache:warmup
  - php bin/console doctrine:migrations:migrate --no-interaction
script:
  - cat codecov.yml | curl --data-binary @- https://codecov.io/validate
  - php bin/phpunit --coverage-clover=codecov.xml
  - bash <(curl -s https://codecov.io/bash)
before_install:
  - chmod +x ./deploy.sh
  - sudo apt-get install sshpass
  - mysql -e 'CREATE DATABASE IF NOT EXISTS tf_test;'
install:
  - composer install
after_success:
  - ./deploy.sh
