language: php
php:
  - '7.1'
sudo: false
cache:
  directories:
  - "$HOME/.composer/cache/files"
before_install:
  - chmod +x ./deploy.sh
  - sudo apt-get install lftp sshpass
install:
  composer install
after_success:
  - ./deploy.sh
  on:
      - master