language: php
php:
    - '7.1'

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

before_install:
  - chmod +x ./deploy.sh
install:
    - composer install

after_success:
    - ./deploy.sh