language: php
php:
  - '7.1'
sudo: false
cache:
  directories:
  - "$HOME/.composer/cache/files"
services:
  - mysql
before_script:
  - php bin/console --env=test cache:warmup
  - php bin/console doctrine:migrations:migrate --no-interaction
script:
  - php bin/phpunit --filter 'App\\Tests\\Controller' --coverage-clover=controller.xml
  - php bin/phpunit --filter 'App\\Tests\\Form\\Type' --coverage-clover=formtype.xml
  - php bin/phpunit --filter 'App\\Tests\\Repository' --coverage-clover=repository.xml
  - php bin/phpunit --filter 'App\\Tests\\Services' --coverage-clover=service.xml
  - php bin/phpunit --filter 'App\\Tests\\Security' --coverage-clover=security.xml
before_install:
  - chmod +x ./deploy.sh
  - sudo apt-get install sshpass
  - mysql -e 'CREATE DATABASE IF NOT EXISTS tf_test;'
install:
  - composer install
after_success:
  - bash <(curl -s https://codecov.io/bash) -c -F controllers
  - bash <(curl -s https://codecov.io/bash) -c -F formtype
  - bash <(curl -s https://codecov.io/bash) -c -F repository
  - bash <(curl -s https://codecov.io/bash) -c -F service
  - bash <(curl -s https://codecov.io/bash) -c -F security
  - ./deploy.sh
